### ISSUE TITLE
Error: spawn /.../wasm-ld ENOENT

### ISSUE THREAD

**Issue by Jonas-Metzger** [zippiehq/quickjs-truebit#1]
Via browserify, I obtained a self-contained `bundle.js` and it successfully executes via `qjs bundle.js`, logging the result to the console. I can also compile it to an executable via `qjsc bundle.js -o executable`, and run it via `./executable`.

However, if I execute:

```
metzgerj:~/CoaseContract/pagesigner/webextension/content/pgsg-node/quickjs-truebit$ node ../wasi-truebit/prepare.js bundle.js --run --debug --out dist --float --file stdout.dta --file main.js
```

I get the following error:

```
/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/wasi-sdk-12.0/bin/wasm-ld -o initial.wasm --import-memory --allow-undefined-file=/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/undefined-allowed.syms --stack-first --export=__heap_base --export=__data_end --export=__global_base -z stack-size=16777216 bundle.js /home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/libtruebit.wasm /home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/softfloat.wasm --export f32_mul --export f32_add --export f32_eq --export f32_to_ui32 --export f32_to_ui64 --export f32_to_i32 --export f32_to_i64 --export f32_to_f64 --export f32_sub --export f32_div --export f32_rem --export f32_le --export f32_sqrt --export f32_lt --export f64_mul --export f64_add --export f64_eq --export f64_to_ui32 --export f64_to_ui64 --export f64_to_i32 --export f64_to_i64 --export f64_to_f32 --export f64_sub --export f64_div --export f64_rem --export f64_le --export f64_sqrt
--export f64_lt --export f64_min --export f64_max --export f32_min --export f32_max --export f64_neg --export f64_abs --export f32_neg --export f32_abs --export f64_ne --export f64_ge --export f64_gt --export f32_ne --export f32_ge --export f32_gt --export f64_floor --export f64_ceil --export f64_trunc --export f64_nearest --export f32_floor --export f32_ceil --export f32_trunc --export f32_nearest --export f32_trunc_i32 --export f32_trunc_ui32 --export f64_trunc_i32 --export f64_trunc_ui32 --export f32_trunc_i64 --export f32_trunc_ui64 --export f64_trunc_i64 --export f64_trunc_ui64 --export f64_copysign --export f32_copysign --export ui32_to_f32 --export i32_to_f32 --export ui64_to_f32 --export i64_to_f32 --export ui64_to_f64 --export ui32_to_f64 --export i32_to_f64 --export i64_to_f64 --export i64_to_f64
error  Error: spawn /home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/wasi-sdk-12.0/bin/wasm-ld ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/wasi-sdk-12.0/bin/wasm-ld',
  path: '/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/wasi-sdk-12.0/bin/wasm-ld',
  spawnargs: [
    '-o',
    'initial.wasm',
    '--import-memory',
    '--allow-undefined-file=/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/undefined-allowed.syms',
    '--stack-first',
    '--export=__heap_base',
    '--export=__data_end',
    '--export=__global_base',
    '-z',
    'stack-size=16777216',
    'bundle.js',
    '/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/libtruebit.wasm',
    '/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/softfloat.wasm',
    '--export',
    'f32_mul',
    '--export',
    'f32_add',
    '--export',
    'f32_eq',
    '--export',
    'f32_to_ui32',
    '--export',
    'f32_to_ui64',
    '--export',
    'f32_to_i32',
    '--export',
    'f32_to_i64',
    '--export',
    'f32_to_f64',
    '--export',
    'f32_sub',
    '--export',
    'f32_div',
    '--export',
    'f32_rem',
    '--export',
    'f32_le',
    '--export',
    'f32_sqrt',
    '--export',
    'f32_lt',
    '--export',
    'f64_mul',
    '--export',
    'f64_add',
    '--export',
    'f64_eq',
    '--export',
    'f64_to_ui32',
    '--export',
    'f64_to_ui64',
    '--export',
    'f64_to_i32',
    '--export',
    'f64_to_i64',
    '--export',
    'f64_to_f32',
    '--export',
    'f64_sub',
    '--export',
    'f64_div',
    '--export',
    'f64_rem',
    '--export',
    'f64_le',
    '--export',
    'f64_sqrt',
    '--export',
    'f64_lt',
    '--export',
    'f64_min',
    '--export',
    'f64_max',
    '--export',
    'f32_min',
    '--export',
    'f32_max',
    '--export',
    'f64_neg',
    '--export',
    'f64_abs',
    '--export',
    'f32_neg',
    '--export',
    'f32_abs',
    '--export',
    'f64_ne',
    '--export',
    'f64_ge',
    '--export',
    'f64_gt',
    '--export',
    'f32_ne',
    '--export',
    'f32_ge',
    '--export',
    'f32_gt',
    '--export',
    'f64_floor',
    '--export',
    ... 51 more items
  ],
  cmd: '/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/wasi-sdk-12.0/bin/wasm-ld -o initial.wasm --import-memory --allow-undefined-file=/home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/undefined-allowed.syms --stack-first --export=__heap_base --export=__data_end --export=__global_base -z stack-size=16777216 bundle.js /home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/libtruebit.wasm /home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/softfloat.wasm --export f32_mul --export f32_add --export f32_eq --export f32_to_ui32 --export f32_to_ui64 --export f32_to_i32 --export f32_to_i64 --export f32_to_f64 --export f32_sub --export f32_div --export f32_rem --export f32_le --export f32_sqrt --export f32_lt --export f64_mul --export f64_add --export f64_eq --export f64_to_ui32 --export f64_to_ui64 --export f64_to_i32 --export f64_to_i64 --export f64_to_f32 --export f64_sub --export f64_div --export f64_rem --export f64_le --export f64_sqrt --export f64_lt --export f64_min --export f64_max --export f32_min --export f32_max --export f64_neg --export f64_abs --export f32_neg --export f32_abs --export f64_ne --export f64_ge --export f64_gt --export f32_ne --export f32_ge --export f32_gt --export f64_floor --export f64_ceil --export f64_trunc --export f64_nearest --export f32_floor --export f32_ceil --export f32_trunc --export f32_nearest --export f32_trunc_i32 --export f32_trunc_ui32 --export f64_trunc_i32 --export f64_trunc_ui32 --export f32_trunc_i64 --export
f32_trunc_ui64 --export f64_trunc_i64 --export f64_trunc_ui64 --export f64_copysign --export f32_copysign --export ui32_to_f32 --export i32_to_f32 --export ui64_to_f32 --export i64_to_f32 --export ui64_to_f64 --export ui32_to_f64 --export i32_to_f64 --export i64_to_f64 --export i64_to_f64'
}
(node:1060) UnhandledPromiseRejectionWarning: Error: spawn /home/metzgerj/CoaseContract/pagesigner/webextension/content/pgsg-node/wasi-truebit/wasi-sdk-12.0/bin/wasm-ld ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

How do I fix this? Thanks a lot!

**Comment by Jonas-Metzger** [comment]
My fault, forgot to run make in either repo.
